# Generated by Django 5.1 on 2024-10-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_billing_address_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='order_shipping_address',
        ),
    ]
